# Generated by Django 3.1.4 on 2021-01-10 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Генеральный Директор', 'Генеральный Директор'), ('Шеф Повар', 'Шеф Повар'), ('Повар', 'Повар'), ('Стажёр', 'Стажёр')], default='Стажёр', max_length=25, verbose_name='Должность')),
                ('education', models.CharField(choices=[('Bachelor', 'Бакалавр'), ('College', 'Техникум или Коледж'), ('Self-Educated', 'Самоучка')], default='Bachelor', max_length=30, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Реальный стаж работы')),
                ('companies', models.CharField(max_length=255, verbose_name='История Работы')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
