# Generated by Django 3.1.4 on 2021-01-10 09:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='breakfasts', verbose_name='Фотография')),
                ('price', models.CharField(max_length=35, verbose_name='Цена')),
                ('ingredients', models.CharField(max_length=35, verbose_name='Ингредиенты')),
                ('date_to_present', models.DateTimeField(verbose_name='Актуально до')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='dinners', verbose_name='Фотография')),
                ('price', models.CharField(max_length=35, verbose_name='Цена')),
                ('ingredients', models.CharField(max_length=35, verbose_name='Ингредиенты')),
                ('date_to_present', models.DateTimeField(verbose_name='Актуально до')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Lanch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='lanches', verbose_name='Фотография')),
                ('price', models.CharField(max_length=35, verbose_name='Цена')),
                ('ingredients', models.CharField(max_length=35, verbose_name='Ингредиенты')),
                ('date_to_present', models.DateTimeField(verbose_name='Актуально до')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('wine_image', models.ImageField(upload_to='wines', verbose_name='Фото')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('category', models.CharField(choices=[('Sweet', 'Сладкое'), ('Half-Sweet', 'Полу-Сладкое'), ('Dry', 'Cухое'), ('Half-Dry', 'Полу-Сухое')], default='Сладкое', max_length=25, verbose_name='Категория')),
                ('priority', models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Приоритет')),
                ('color', models.CharField(choices=[('White', 'Белое'), ('Red', 'Красное'), ('Pink', 'Розовое')], default='Белое', max_length=10, verbose_name='Цвет')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Цена')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('rate', models.ManyToManyField(related_name='wines', to='menu.Rate')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Главное Блюдо')),
                ('kitchen', models.CharField(max_length=30, verbose_name='Кухня')),
                ('meal_image', models.ImageField(upload_to='meals', verbose_name='Фото')),
                ('ingredients', models.CharField(max_length=255, verbose_name='Ингредиенты')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Цена')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('rate', models.ManyToManyField(related_name='primary_meals', to='menu.Rate')),
            ],
        ),
    ]
