# Generated by Django 3.1.4 on 2021-01-10 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Номер Телефона')),
                ('date', models.DateField(verbose_name='Дата Бронирования')),
                ('time', models.TimeField(verbose_name='Время Бронирования')),
                ('persons', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], default='1', max_length=5, verbose_name='Количество человек')),
                ('message', models.TextField(verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания Бронирования')),
                ('reservator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
